name: Extract Data CVM

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas fastparquet

      - name: execute py script
        run: python extract.py

      - name: commit and push data CVM
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (git add -A && git commit -m "Atualiza os informes no repositório automaticamente")
          git push
        if: success()
